name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6

  #  For Api request
  dio: ^5.4.0

  #  For loader
  loader_overlay: ^4.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 700

